### PR TITLE
feat(minor): add twitter api error details to log

### PR DESCRIPTION
**Pull request by iloveitaly**

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
What information does this display that's not displayed if you include just the root error object? Can you show us a repro?

**Comment by iloveitaly** [comment]
I lost the terminal content: basically I was just getting a generic 403 authorization. Getting the full object in the error message actually told me specifically what is wrong.

**Review by simoneb — COMMENTED** [review]
Can you update the tests to get CI to pass?

**Comment by iloveitaly** [comment]
@simoneb the linked issue one is failing (I bet that's ok), and I think I fixed the broken test.

**Review by simoneb — APPROVED** [review]
LGTM

**Pull request merged**
